meta_product_name: "VenMu"
meta_title: "VenM̃u - Your Music. New Places"
meta_description: "VenM̃u finds places playing the music you want to hear. Search by genre or connect through Spotify for a truly unique experience."
meta_image: "meta_image.jpg" # should exist in `app/assets/images/`
twitter_account: "@VenMu3"   # required for Twitter Cards